# Generated by Django 3.0.8 on 2021-04-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangManGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret_word', models.CharField(max_length=255)),
                ('correct_guesses', models.CharField(max_length=255)),
                ('incorrect_guesses', models.CharField(default='', max_length=8)),
                ('game_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('WIN', 'Win'), ('LOSS', 'Loss')], default='IN_PROGRESS', max_length=11)),
            ],
        ),
    ]
